# Generated by Django 5.2.3 on 2025-06-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_profile',
            field=models.ImageField(default='userprofile/avatar.svg', null=True, upload_to='userprofile'),
        ),
    ]
